// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3rydOf7Z8SHa9ip0VrgAPNtCreJHkMiE',
    appId: '1:530607594415:web:44bdda0a57480c5e1f2d5a',
    messagingSenderId: '530607594415',
    projectId: 'myicc-lyon',
    authDomain: 'myicc-lyon.firebaseapp.com',
    storageBucket: 'myicc-lyon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfUY2f_BvbSYwTpCzA-7irba2rZOcx7aU',
    appId: '1:530607594415:android:8d02462b1bad0ab81f2d5a',
    messagingSenderId: '530607594415',
    projectId: 'myicc-lyon',
    storageBucket: 'myicc-lyon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlCfCBcYXQkJD6139ozUBWlsvzkgVv1QE',
    appId: '1:530607594415:ios:bb9f5e63793fad0a1f2d5a',
    messagingSenderId: '530607594415',
    projectId: 'myicc-lyon',
    storageBucket: 'myicc-lyon.appspot.com',
    iosClientId: '530607594415-dml7dt9mqb1hlc7lc9uonujrd10sg7m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myicclyon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlCfCBcYXQkJD6139ozUBWlsvzkgVv1QE',
    appId: '1:530607594415:ios:bb9f5e63793fad0a1f2d5a',
    messagingSenderId: '530607594415',
    projectId: 'myicc-lyon',
    storageBucket: 'myicc-lyon.appspot.com',
    iosClientId: '530607594415-dml7dt9mqb1hlc7lc9uonujrd10sg7m6.apps.googleusercontent.com',
    iosBundleId: 'com.example.myicclyon',
  );
}
